name: Build and Deploy with Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-web-app:latest .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-web-app:latest

    - name: Deploy to Azure Container Instance with Storage
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name python-web-app \
          --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/python-web-app:latest \
          --dns-name-label python-web-app-$(date +%s) \
          --ports 5000 \
          --azure-file-volume-share-name ${{ secrets.STORAGE_FILE_SHARE_NAME }} \
          --azure-file-volume-account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --azure-file-volume-account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --azure-file-volume-mount-path /app/data
